version: '3.8'

services:
  ros_camera:
    image: "camera_image"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: camera_container
    ports:
      - "9091:9090"  # Expose the ROS master port
    devices:
      - "/dev/video0:/dev/video0"  # Map the camera's USB device to the container
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # Map the Arduino's USB device to the container
    environment:
      - PYTHONUNBUFFERED=1  # Ensures Python output is visible in real-time
      - DISPLAY=${DISPLAY}  # Set the display environment variable
      - QT_X11_NO_MITSHM=1  # Disable MIT-SHM for better compatibility
    tty: true  # Keep the container running for ROS commands
    privileged: true  # Allow access to hardware devices
    networks:
      - ros_node  # Attach to the existing ros_node network

networks:
  ros_node:
    external: true
